const SCM_CONFIG = [{
  in: {
    lang: 'EN-IN',
    currencyCode: 'INR',
    currencySymbol:'₹',
    ga_id: 'UA-109515030-9',
    phone_code: '+91',
    facebookurl: '//www.facebook.com/XiaomiIndia',
    youtubeurl: '//www.youtube.com/user/MiIndiaOfficial',
    twitterurl: '//twitter.com/XiaomiIndia',
    instagramurl: '//www.instagram.com/xiaomiindia',
  },
  es: {
    lang: 'EN-ES',
    currencyCode: 'EUR',
    currencySymbol:'€',
    ga_id: 'UA-51415204-49',
    phone_code: '+34',
    facebookurl: '//www.facebook.com/XiaomiEspana',
    youtubeurl: '//www.linkedin.com/company/xiaomi-technology',
    twitterurl: '//twitter.com/XiaomiEspana',
    instagramurl: '//www.instagram.com/XiaomiEspana',
  },
  id: {
    lang: 'EN-ID',
    currencyCode: 'IDR',
    currencySymbol:'Rp ',
    ga_id: 'UA-51415204-10',
    phone_code: '+62',
    facebookurl: '//www.facebook.com/XiaomiIndonesia',
    youtubeurl: '//www.instagram.com/xiaomiindonesia',
    twitterurl: '//www.twitter.com/xiaomiindonesia',
  },
  ru: {
    lang: 'EN-RU',
    currencyCode: 'RUB',
    currencySymbol:'₽',
    ga_id: 'UA-51415204-10',
    phone_code: '+62',
    facebookurl: '//www.facebook.com/XiaomiRussia',
  },
  it: {
    lang: 'EN-IT',
    currencyCode: 'EUR',
    currencySymbol:'€',
    ga_id: 'UA-51415204-51',
    phone_code: '+62',
    facebookurl: '//www.facebook.com/XiaomiItalia',
    youtubeurl: '//www.linkedin.com/company/xiaomi-technology',
    twitterurl: '//twitter.com/XiaomiEspana',
    instagramurl: '//www.instagram.com/xiaomi.italia',
  },
  fr: {
    lang: 'EN-FR',
    currencyCode: 'EUR',
    currencySymbol:'€',
    ga_id: '',
    phone_code: '+62',
    facebookurl: '//www.facebook.com/xiaomifrance',
    youtubeurl: '//www.linkedin.com/company/xiaomi-technology',
    twitterurl: '//twitter.com/xiaomi_france',
    instagramurl: '//www.instagram.com/xiaomi_france',
  }
}]
export default {
  SCM_CONFIG
}